# Generated by Django 4.0.3 on 2022-03-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
